# Generated by Django 4.1.7 on 2023-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AREA_NM', models.CharField(max_length=20)),
                ('LIVE_PPLTN_STTS', models.IntegerField()),
                ('AREA_CONGEST_LVL', models.CharField(max_length=10)),
                ('AREA_CONGEST_MSG', models.CharField(max_length=255)),
                ('AREA_PPLTN_MIN', models.IntegerField()),
                ('AREA_PPLTN_MAX', models.IntegerField()),
            ],
        ),
    ]
